import type { Metadata } from "next";
import "./globals.css";
import "@/styles/tw-animate.css";
import { NavigationDock } from "@/components/NavigationDock";
import { Footer } from "@/components/Footer";
import { TracingBeamWrapper } from "@/components/TracingBeamWrapper";

export const metadata: Metadata = {
  title: "Hexagon Digital Services Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-zinc-950 text-zinc-100 flex flex-col antialiased min-h-screen">
        <NavigationDock />
        <TracingBeamWrapper>
          <main className="flex-1 flex flex-col min-h-screen relative pt-8">
            {children}
            <Footer />
          </main>
        </TracingBeamWrapper>
      </body>
    </html>
  );
}
